//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Secondary Structure Prediction.rc
//
#define IDD_SECONDARYSTRUCTUREPREDICTION_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDC_ADDBRAIN                    1000
#define IDC_BRAINLIST                   1002
#define IDC_REMOVEBRAIN                 1003
#define IDC_WEIGHT                      1006
#define IDC_SETWEIGHT                   1007
#define IDC_SETWEIGHT2                  1008
#define IDC_EDIT4                       1009
#define IDC_BROWSE2                     1010
#define IDC_PREDICT                     1011
#define IDC_STEPS                       1012
#define IDC_SETSTEPS                    1013
#define IDC_LIST3                       1014
#define IDC_ADDINPUT                    1015
#define IDC_REMOVEINPUT                 1016
#define IDC_INPUTWEIGHT                 1017
#define IDC_WEIGHT2                     1017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
